name: Build and Test Wingman-os

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib qemu-system-x86 binutils

      - name: Build kernel
        run: make

      - name: Run QEMU and capture output
        run: |
          timeout 2s qemu-system-i386 -nographic -kernel kernel.bin > qemu.log 2>&1 || true
          echo "===== QEMU OUTPUT ====="
          cat qemu.log
          echo "======================="
          
          # Test: kontrollera om din boot-text syns
          if ! grep -q "Hello from Wingman-OS" qemu.log; then
            echo "❌ Expected output not found in QEMU log"
            exit 1
          fi
          echo "✅ Boot message found!"
