name: WingmanOS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y nasm qemu-system-x86

      - name: Build bootloader
        run: nasm -f bin boot.asm -o boot.bin

      - name: Dump boot.bin (hex view)
        run: hexdump -C boot.bin

      - name: Run in QEMU
        run: |
          set -e
          OUTPUT=$(qemu-system-x86_64 -drive format=raw,file=boot.bin \
            -nographic -serial mon:stdio -d guest_errors -no-reboot)
          echo "=== QEMU OUTPUT ==="
          echo "$OUTPUT"
          echo "==================="

          if echo "$OUTPUT" | grep -q "hello worl"; then
            echo "✅ Bootloader skrev hello world!"
          else
            echo "❌ Bootloader-output saknas eller fel"
            exit 1
          fi
